// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReseauUniversitaire.Data;

#nullable disable

namespace ReseauUniversitaire.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628152650_AjoutMediasPublication")]
    partial class AjoutMediasPublication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReseauUniversitaire.Models.Abonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonneId")
                        .HasColumnType("integer");

                    b.Property<int>("AbonnementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAbonnement")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AbonneId");

                    b.HasIndex("AbonnementId");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Canal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EstAdminSeulement")
                        .HasColumnType("boolean");

                    b.Property<int>("GroupeId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.ToTable("Canaux");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("PublicationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicationId");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Participant1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Participant2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Participant1Id");

                    b.HasIndex("Participant2Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.EvaluationRessource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Note")
                        .HasColumnType("integer");

                    b.Property<int>("RessourceId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RessourceId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("EvaluationsRessource");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Evenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("integer");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganisateurId")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("OrganisateurId");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EstPrive")
                        .HasColumnType("boolean");

                    b.Property<int?>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FiliereId");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateLike")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublicationId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.MembreGroupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdhesion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DemandeEnAttente")
                        .HasColumnType("boolean");

                    b.Property<int>("GroupeId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("MembresGroupe");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLu")
                        .HasColumnType("boolean");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer");

                    b.Property<string>("FichierUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ExpediteurId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.MessageCanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CanalId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer");

                    b.Property<string>("FichierUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanalId");

                    b.HasIndex("ExpediteurId");

                    b.ToTable("MessagesCanaux");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean");

                    b.Property<string>("LienUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstSignale")
                        .HasColumnType("boolean");

                    b.Property<string>("FichierNom")
                        .HasColumnType("text");

                    b.Property<string>("FichierUrl")
                        .HasColumnType("text");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("GroupeId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Ressource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FichierUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<string>("Matiere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NbTelechargements")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("FiliereId");

                    b.ToTable("Ressources");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Signalement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateSignalement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstTraite")
                        .HasColumnType("boolean");

                    b.Property<int>("PublicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("PublicationId");

                    b.ToTable("Signalements");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<int?>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FiliereId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Abonnement", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Abonne")
                        .WithMany("Abonnements")
                        .HasForeignKey("AbonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "AbonnementUtilisateur")
                        .WithMany("Abonnes")
                        .HasForeignKey("AbonnementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonne");

                    b.Navigation("AbonnementUtilisateur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Canal", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Groupe", "Groupe")
                        .WithMany("Canaux")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Commentaire", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Commentaire", "Parent")
                        .WithMany("Reponses")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReseauUniversitaire.Models.Publication", "Publication")
                        .WithMany("Commentaires")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Parent");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Conversation", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Participant1")
                        .WithMany()
                        .HasForeignKey("Participant1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Participant2")
                        .WithMany()
                        .HasForeignKey("Participant2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant1");

                    b.Navigation("Participant2");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.EvaluationRessource", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Ressource", "Ressource")
                        .WithMany("Evaluations")
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ressource");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Evenement", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Organisateur")
                        .WithMany()
                        .HasForeignKey("OrganisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("Organisateur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Groupe", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Filiere", "Filiere")
                        .WithMany("Groupes")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Like", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Publication", "Publication")
                        .WithMany("Likes")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.MembreGroupe", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Groupe", "Groupe")
                        .WithMany("Membres")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Utilisateur")
                        .WithMany("Groupes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Message", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Expediteur")
                        .WithMany("MessagesEnvoyes")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Expediteur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.MessageCanal", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Canal", "Canal")
                        .WithMany("Messages")
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Expediteur")
                        .WithMany()
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canal");

                    b.Navigation("Expediteur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Notification", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Publication", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Auteur")
                        .WithMany("Publications")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Groupe", "Groupe")
                        .WithMany("Publications")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Auteur");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Ressource", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Filiere", "Filiere")
                        .WithMany()
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Auteur");

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Signalement", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Utilisateur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReseauUniversitaire.Models.Publication", "Publication")
                        .WithMany("Signalements")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Utilisateur", b =>
                {
                    b.HasOne("ReseauUniversitaire.Models.Filiere", "Filiere")
                        .WithMany("Etudiants")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Canal", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Commentaire", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Filiere", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Groupes");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Groupe", b =>
                {
                    b.Navigation("Canaux");

                    b.Navigation("Membres");

                    b.Navigation("Publications");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Publication", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Likes");

                    b.Navigation("Signalements");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Ressource", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("ReseauUniversitaire.Models.Utilisateur", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("Abonnes");

                    b.Navigation("Groupes");

                    b.Navigation("MessagesEnvoyes");

                    b.Navigation("Notifications");

                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
